"""Regressions for the third review round.

These are the ones a live demo would expose: add a second patient, re-run the
build, drop in a changed file. Each test states the defect it pins.
"""
from __future__ import annotations

import json
import pathlib
import shutil
import tempfile
import unittest

from backbone import queries as Q
from backbone import reconcile
from backbone.ingest import TEXT_SUFFIXES, ingest_dir, ingest_path
from backbone.store import Store

HDR = "Harbor Grove Behavioral Health"

# A second patient, entirely independent of the supplied corpus.
PLAN_B = (f"Document ID: MP-P1\n{HDR} | Outpatient treatment plan\n"
          "Marek Dvorak | DOB 1979-11-11 | MRN HG-M700\n"
          "Episode dates: 2026-02-02 through 2026-02-15\n"
          "signed 2026-02-02\n"
          "Local treatment participation goal: at least 2 therapy days and at "
          "least 90 minutes of patient-present therapy in each Monday-Sunday "
          "week. Patient-present individual, group, and family therapy "
          "contribute to the minute goal. Medication management and care "
          "coordination do not contribute.\n")
NOTE_B = (f"Document ID: MP-N1\n{HDR} | Individual psychotherapy\n"
          "Marek Dvorak | DOB 1979-11-11 | MRN HG-M700 | Encounter HG-E700\n"
          "Service date 2026-02-03\n"
          "Patient contact: 09:00-09:45 | Completed: 45 minutes\n")
# an administrative receipt for patient B, which must be rejected for B and
# must never appear in patient A's answer
RECEIPT_B = (f"Document ID: MP-A1\n{HDR} | Administrative chart extract\n"
             "Marek Dvorak | DOB 1979-11-11 | MRN HG-M700\n"
             "Service date 2026-02-04 | Encounter HG-E701\n\n"
             "SECTION A - AUTOGENERATED PROGRESS NOTE\n"
             "Status: DRAFT - UNSIGNED - system populated from template\n"
             "Scheduled service: Skills group, 10:00-11:30\n"
             "Template attendance text: Patient attended the full session.\n")


def _two_patient_store(db: str):
    for s in ("", "-wal", "-shm"):
        p = pathlib.Path(db + s)
        if p.exists():
            p.unlink()
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="bb_mp_"))
    for f in sorted(pathlib.Path("documents").glob("*.txt")):
        shutil.copy(f, tmp / f.name)
    (tmp / "mp_plan.txt").write_text(PLAN_B, encoding="utf-8")
    (tmp / "mp_note.txt").write_text(NOTE_B, encoding="utf-8")
    (tmp / "mp_receipt.txt").write_text(RECEIPT_B, encoding="utf-8")
    st = Store(db)
    ingest_dir(st, tmp)
    reconcile.reconcile_all(st)
    return st, tmp


class DecisionLogScoping(unittest.TestCase):
    """#1 Decisions must be per patient, and must not accumulate."""

    @classmethod
    def setUpClass(cls):
        cls.st, cls.tmp = _two_patient_store("out/test_mp.db")

    @classmethod
    def tearDownClass(cls):
        cls.st.close()
        shutil.rmtree(cls.tmp, ignore_errors=True)

    def test_both_patients_exist(self):
        self.assertEqual(sorted(self.st.patients()), ["HG-M042", "HG-M700"])

    def test_every_decision_is_stamped_with_a_patient(self):
        unstamped = self.st.q(
            "SELECT rule_id, field, COUNT(*) n FROM decisions"
            " WHERE patient_mrn IS NULL GROUP BY 1,2")
        self.assertEqual([dict(r) for r in unstamped], [],
                         "a decision with no patient cannot be scoped or cleared")

    def test_one_patients_answer_does_not_cite_the_others_claims(self):
        res = Q.session_counts(self.st, "HG-M042", "2026-01-05", "2026-01-30")
        blob = json.dumps(res)
        self.assertNotIn("HG-M700", blob)
        self.assertNotIn("MP-N1", blob)
        self.assertNotIn("MP-A1", blob,
                         "the other patient's rejected draft note leaked into "
                         "this patient's exclusion list")
        # and the converse
        other = json.dumps(Q.session_counts(self.st, "HG-M700",
                                            "2026-02-02", "2026-02-15"))
        self.assertNotIn("HG-E110", other)
        self.assertNotIn("BH-D1", other)

    def test_rebuilding_does_not_duplicate_decisions(self):
        before = self.st.q1("SELECT COUNT(*) n FROM decisions")["n"]
        per_patient = {
            m: self.st.q1("SELECT COUNT(*) n FROM decisions WHERE patient_mrn=?",
                          (m,))["n"] for m in self.st.patients()}
        for _ in range(3):
            reconcile.reconcile_all(self.st)
        after = self.st.q1("SELECT COUNT(*) n FROM decisions")["n"]
        self.assertEqual(before, after,
                         "reconciling again appended another copy of every "
                         "decision that is not tied to an event")
        self.assertEqual(per_patient, {
            m: self.st.q1("SELECT COUNT(*) n FROM decisions WHERE patient_mrn=?",
                          (m,))["n"] for m in self.st.patients()})

    def test_exclusion_list_does_not_grow_on_rebuild(self):
        def n_caveats():
            r = Q.session_counts(self.st, "HG-M042", "2026-01-05", "2026-01-30")
            return len(r["caveats"])
        first = n_caveats()
        reconcile.reconcile_patient(self.st, "HG-M042")
        reconcile.reconcile_patient(self.st, "HG-M042")
        self.assertEqual(first, n_caveats(),
                         "DEV-01's exclusion list repeated after a rebuild")

    def test_reconciling_one_patient_leaves_the_other_untouched(self):
        before = Q.minutes(self.st, "HG-M700", "2026-02-02", "2026-02-15")["value"]
        reconcile.reconcile_patient(self.st, "HG-M042")
        after = Q.minutes(self.st, "HG-M700", "2026-02-02", "2026-02-15")["value"]
        self.assertEqual(before["total_minutes"], after["total_minutes"])

    def test_supplied_corpus_answers_are_unchanged_by_a_second_patient(self):
        v = Q.session_counts(self.st, "HG-M042", "2026-01-05", "2026-01-30")["value"]
        self.assertEqual(v["sessions"], 12)
        self.assertEqual(v["distinct_days"], 11)
        m = Q.minutes(self.st, "HG-M042", "2026-01-05", "2026-01-30")["value"]
        self.assertEqual(m["total_minutes"], [585, 595])


class CorrectionsTable(unittest.TestCase):
    """#2 The corrections table must actually be written."""

    @classmethod
    def setUpClass(cls):
        for s in ("", "-wal", "-shm"):
            p = pathlib.Path("out/test_corr.db" + s)
            if p.exists():
                p.unlink()
        cls.st = Store("out/test_corr.db")
        ingest_dir(cls.st, pathlib.Path("documents"))
        reconcile.reconcile_all(cls.st)

    @classmethod
    def tearDownClass(cls):
        cls.st.close()

    def test_the_correction_relationship_is_a_row(self):
        rows = [dict(r) for r in self.st.corrections("HG-M042")]
        self.assertEqual(len(rows), 1, rows)
        r = rows[0]
        self.assertEqual(r["target_enc"], "HG-E110")
        self.assertEqual(r["target_field"], "departure")
        self.assertEqual(r["old_value"], "11:30")
        self.assertEqual(r["new_value"], "11:15")

    def test_it_carries_its_source_span(self):
        r = dict(self.st.corrections("HG-M042")[0])
        raw = pathlib.Path("documents/"
                           "BH-D103_attendance_correction_2026-01-20.txt"
                           ).read_text(encoding="utf-8")
        self.assertEqual(raw[r["quote_start"]:r["quote_end"]], r["quote"])
        self.assertIn("11:15", r["quote"])

    def test_re_ingesting_does_not_duplicate_the_row(self):
        ingest_dir(self.st, pathlib.Path("documents"), force=True)
        reconcile.reconcile_all(self.st)
        self.assertEqual(len(self.st.corrections("HG-M042")), 1)


class DocumentIntake(unittest.TestCase):
    """#3 Non-.txt files must not be skipped, and an edited file must replace."""

    def test_more_than_txt_is_picked_up(self):
        self.assertIn(".md", TEXT_SUFFIXES)
        self.assertIn(".csv", TEXT_SUFFIXES)
        for s in ("", "-wal", "-shm"):
            p = pathlib.Path("out/test_intake.db" + s)
            if p.exists():
                p.unlink()
        tmp = pathlib.Path(tempfile.mkdtemp(prefix="bb_in_"))
        (tmp / "note.md").write_text(NOTE_B, encoding="utf-8")
        (tmp / "plan.text").write_text(PLAN_B, encoding="utf-8")
        (tmp / "scan.png").write_bytes(b"\x89PNG not text")
        st = Store("out/test_intake.db")
        rep = ingest_dir(st, tmp)
        self.assertEqual(rep["ingested"], 2, rep)
        self.assertIn("scan.png", rep["skipped_files"],
                      "a file that cannot be read must be reported, not "
                      "silently dropped")
        self.assertEqual(st.patients(), ["HG-M700"])
        st.close()
        shutil.rmtree(tmp, ignore_errors=True)

    def test_a_file_edited_in_place_replaces_its_old_claims(self):
        for s in ("", "-wal", "-shm"):
            p = pathlib.Path("out/test_edit.db" + s)
            if p.exists():
                p.unlink()
        tmp = pathlib.Path(tempfile.mkdtemp(prefix="bb_ed_"))
        f = tmp / "note.txt"
        f.write_text(PLAN_B, encoding="utf-8")
        (tmp / "n.txt").write_text(NOTE_B, encoding="utf-8")
        st = Store("out/test_edit.db")
        ingest_dir(st, tmp)
        reconcile.reconcile_all(st)
        first = Q.minutes(st, "HG-M700", "2026-02-02", "2026-02-15")["value"]
        self.assertEqual(first["total_minutes"], [45, 45])

        # the note is corrected in place: 45 minutes becomes 75
        (tmp / "n.txt").write_text(
            NOTE_B.replace("09:00-09:45 | Completed: 45 minutes",
                           "09:00-10:15 | Completed: 75 minutes"),
            encoding="utf-8")
        r = ingest_path(st, tmp / "n.txt")
        self.assertTrue(r.get("replaced"), r)
        reconcile.reconcile_all(st)
        after = Q.minutes(st, "HG-M700", "2026-02-02", "2026-02-15")["value"]
        self.assertEqual(after["total_minutes"], [75, 75],
                         "the superseded version's claims were still counted")
        self.assertEqual(
            st.q1("SELECT COUNT(*) n FROM documents WHERE filename='n.txt'")["n"],
            1, "the old document row survived the edit")
        st.close()
        shutil.rmtree(tmp, ignore_errors=True)


class PresenceByContext(unittest.TestCase):
    """#4 A disposition field must outrank a passing mention."""

    def test_status_field_beats_a_cancellation_mentioned_elsewhere(self):
        from backbone.extract.rules import _presence_detail
        p, cue, _, _ = _presence_detail(
            "Status: Attended. A cancellation notice was sent to other members.",
            "Rowan")
        self.assertEqual(p, "present")
        self.assertEqual(cue, "attended")

    def test_a_sentence_about_the_patient_beats_a_bare_mention(self):
        from backbone.extract.rules import _presence_detail
        p, _, _, _ = _presence_detail(
            "Rowan was present from opening through closing. The January 15 "
            "cancellation is filed separately.", "Rowan")
        self.assertEqual(p, "present")

    def test_a_real_cancellation_is_still_read(self):
        from backbone.extract.rules import _presence_detail
        p, _, _, _ = _presence_detail(
            "The coping skills group scheduled for January 15 is cancelled by "
            "the clinic because of staff illness.", "Rowan")
        self.assertEqual(p, "cancelled")

    def test_equal_authority_conflict_asserts_nothing(self):
        from backbone.extract.rules import _presence_detail
        p, cue, _, amb = _presence_detail(
            "The patient attended. The patient cancellation was recorded.",
            "Rowan")
        self.assertIsNone(p, "a document that says both must not pick one")
        self.assertIsNotNone(amb)
        self.assertIn("attended", amb["competing"])


class MeasureScoreConflict(unittest.TestCase):
    """#5 Two records of one administration with different scores."""

    @classmethod
    def setUpClass(cls):
        docs = {
            "review.txt": (
                f"Document ID: MP-M1\n{HDR} | Measurement review\n"
                "Sena Adeyemi | DOB 1994-04-04 | MRN HG-M701\n"
                "Instrument: PHQ-9 | Patient portal form HG-Q950\n"
                "Completed by patient: 2026-03-02, 08:00 local\n"
                "Total score: 16\n"),
            # a second record of the SAME administration, different score
            "import.txt": (
                f"Document ID: MP-M2\n{HDR} | Administrative import receipt\n"
                "Sena Adeyemi | DOB 1994-04-04 | MRN HG-M701\n"
                "Received into chart: 2026-03-20, 07:00 local\n\n"
                "Measure | Result | Date completed | Source form\n"
                "PHQ-9   | 11     | 2026-03-02     | HG-Q950\n"
                "Import detail: copied result from the March 2 portal form. "
                "This receipt does not document a visit.\n"),
        }
        for s in ("", "-wal", "-shm"):
            p = pathlib.Path("out/test_mconf.db" + s)
            if p.exists():
                p.unlink()
        cls.tmp = pathlib.Path(tempfile.mkdtemp(prefix="bb_mc_"))
        for n, t in docs.items():
            (cls.tmp / n).write_text(t, encoding="utf-8")
        cls.st = Store("out/test_mconf.db")
        ingest_dir(cls.st, cls.tmp)
        reconcile.reconcile_all(cls.st)

    @classmethod
    def tearDownClass(cls):
        cls.st.close()
        shutil.rmtree(cls.tmp, ignore_errors=True)

    def test_it_is_still_one_administration(self):
        self.assertEqual(len(self.st.measures("HG-M701")), 1)

    def test_the_disagreement_is_flagged_not_absorbed(self):
        m = dict(self.st.measures("HG-M701")[0])
        self.assertEqual(m["disputed"], 1,
                         "the second score was silently discarded")
        totals = sorted(c["total"] for c in json.loads(m["total_conflicts"]))
        self.assertEqual(totals, [11.0, 16.0])

    def test_a_decision_records_the_conflict(self):
        rows = self.st.q("SELECT * FROM decisions WHERE rule_id='RULE-MEAS-02'")
        self.assertTrue(rows)
        self.assertIn("different scores", rows[0]["rationale"])

    def test_progress_declines_to_state_a_single_score(self):
        v = Q.progress(self.st, "HG-M701")["value"]
        why = " ".join(s["statement"] + s["why"] for s in v["not_supported"])
        self.assertIn("single score", why)


if __name__ == "__main__":
    unittest.main(verbosity=2)
